### ISSUE TITLE
Incorrect Standard Deviation Calculation

### ISSUE THREAD

**Issue by EthanW92** [mattszymanko/IoTDataKit#1]
### Description

Hi. The current implementation of the `calculateStandardDeviation` function in the `IoTData` class seems to have an issue in certain scenarios. The calculated standard deviation appears to be incorrect when the data contains negative values. This behavior is observed in cases where the mean is a positive value, and the data set includes both positive and negative values.

### Reproducibility

Always

### What is the operating system you're encountering this issue on?

Windows 10 x64

### Steps To Reproduce

1. Create an instance of `IoTData` with a data set containing both positive and negative values.
2. Call the `calculateStandardDeviation` function.

### Agreements

I agree to follow the project's Code of Conduct, and Contribution Guidelines

**Comment by mattszymanko** [comment]
Hello Andrew,

Thanks for the report. I'll look into it as soon as possible and provide an update accordingly.

Best regards,
Matt

**Comment by mattszymanko** [comment]
Hello again Andrew,

After investigating, it does seem to be the case that the current implementation of the `calculateStandardDeviation` function in the `IoTData` class has an issue in certain scenarios. I'll see what I can do and get back to you, also regarding #2. 

Best regards,
Matt

**Comment by mattszymanko** [comment]
Resolved in #2. The issue has been fixed internally and the fix will appear in the upcoming update.
